#!/bin/bash
ROFI_TEXT="Virtual Machines Launcher"
typeset -A menu
menu=(
    ["Kill Everything"]="kvm-killall"
    ["KVM - Android x86"]="virsh start android"
    ["KVM - Fedora 37"]="virsh start fedora"
    ["KVM - macOS 12"]="virsh start macOS"
    ["KVM - Windows 11"]="virsh start win11"
    ["KVM - Xibo"]="virsh start xibo"
    ["Vbox - GLPI"]=" "
    ["Vbox - AD"]=" "
)
launcher_options=(-dmenu -i -lines "${#menu[@]}" -p "${ROFI_TEXT}" \
         "${ROFI_COLORS[@]}" "${ROFI_OPTIONS[@]}") 
launcher=(rofi "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"
if [[ -n $selection ]]
then
    exec ${menu[${selection}]}
fi
